# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Siv3D Playground CI

on:
  push:
    branches: [ "main" ]
    tags: [ v** ]
    paths: [ "siv3d-playground" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "siv3d-playground" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm install
      - run: npm run compile
      - run: |
          npm pack
          mv siv3d-playground-*.tgz siv3d-playground.tgz
      - uses: actions/upload-artifact@v4
        with:
          name: siv3d-playground-npm-package
          path: siv3d-playground.tgz

      - uses: actions/create-release@v1
        if: ${{ contains(github.ref, 'tags/v') }}
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - uses: actions/upload-release-asset@v1
        if: ${{ contains(github.ref, 'tags/v') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: siv3d-playground.tgz
          asset_name: siv3d-playground.tgz
          asset_content_type: application/gzip
